### ISSUE TITLE
Title on MapIconDrawer

### ISSUE THREAD

**Issue by RomeoPavoni** [LocalJoost/WpWinNl#1]
Hi Joost,
can you improve the WpWinNl.MapBindingDemo just adding a working Title on MapIconDrawer binded from public ObservableCollection<PointList> Icons?

I have always error "Unable to cast object of type 'Windows.UI.Xaml.Data.Binding' to type 'System.String'."

Many thanks

**Comment by LocalJoost** [comment]
I can, and I have done so. See the "Italian Cheese" button ;). Don't forget to set the initial location first (secondary command "show area"). I hope this suits your needs

**Comment by RomeoPavoni** [comment]
Very quick response, many thanks!
And of course i like Italian cheese, my favorite is "Monte Veronese" which is from my town!

Btw, i was trying to simply add the Title property to the standard MapIconDrawer xaml element binded to the Icons ObservableCollection.

Is not possible to do in that way without creating a custom drawer? Maybe the xaml properties are not bindable and must be hardcoded?
