### ISSUE TITLE
Brush instead of Color for MapPolylineDrawer

### ISSUE THREAD

**Issue by MrWolfPST** [LocalJoost/WpWinNl#3]
I'm using your library in an UWP project.
I'm trying to make color of the line reactive to changes of SystemAccentColor, but this resource is not usable with ThemeResource markup extension, I can use it only as StaticResource, but in this case changes of resource value is not propagated at the control. SystemControlBackgroundAccentBrush resource can be instead used with ThemeResource

**Comment by MrWolfPST** [comment]
I have browsed your code after my post, and I figured it out that my request is not feasible because also the underlying MapPolyline object expose a Color property instead of Brush.

**Comment by LocalJoost** [comment]
Exactly :)
