### ISSUE TITLE
Binding not working

### ISSUE THREAD

**Issue by Gh0s7** [LocalJoost/WpWinNl#4]
Hi there, what about changing drawers to be `DependencyObject` so that we can bind both `Title` and `ImageUri` in the `MapIconDrawer`? I have a layer with objects of the same type which require different icons, so I can only use binding and it doesn't work.

**Comment by LocalJoost** [comment]
Hi, by the very nature of the way drawers work, making a dependency object from them won't work as it is not a template control. Having said that... will this work for you? https://dotnetbyexample.blogspot.com/2016/05/generic-databinding-for-mapicons-in.html
